openapi: 3.0.3
info:
  title: Storage
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/v1/storage:
    get:
      summary: 'Get all storage'
      operationId: getAllStorage
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - 'Storage Endpoints'
      security: []
    post:
      summary: 'Store a new storage'
      operationId: storeANewStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Storage Endpoints'
      security: []
  '/api/v1/storage/{storage_id}':
    delete:
      summary: 'Delete a storage'
      operationId: deleteAStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Storage Endpoints'
      security: []
    parameters:
      -
        in: path
        name: storage_id
        description: 'The ID of the storage.'
        example: 12
        required: true
        schema:
          type: integer
tags:
  -
    name: 'Storage Endpoints'
    description: "\nEndpoints for managing storage"
