openapi: 3.0.3
info:
  title: Storage
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/api:
    get:
      summary: ''
      operationId: getApiApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'BASE_URL: http://localhost:8000'
      tags:
        - Endpoints
      security: []
  '/api/v1/storage/{user_uuid}':
    get:
      summary: 'Get all storage'
      operationId: getAllStorage
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 404
                  success: false
                  message: 'User not found'
                properties:
                  status:
                    type: integer
                    example: 404
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'User not found'
      tags:
        - 'Storage Endpoints'
      security: []
    post:
      summary: 'Store a new storage'
      operationId: storeANewStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Storage Endpoints'
      security: []
    parameters:
      -
        in: path
        name: user_uuid
        description: ''
        example: 34e3aae3-7933-3eb8-ac64-18a821a2434a
        required: true
        schema:
          type: string
  '/api/v1/storage/{storage_uuid}/{user_uuid}':
    delete:
      summary: 'Delete a storage'
      operationId: deleteAStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Storage Endpoints'
      security: []
    parameters:
      -
        in: path
        name: storage_uuid
        description: ''
        example: 32b83174-94b9-35cf-8e24-be209d2c25dd
        required: true
        schema:
          type: string
      -
        in: path
        name: user_uuid
        description: ''
        example: 1cd895cc-1c4f-4fe4-93c3-26b35df22d80
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
  -
    name: 'Storage Endpoints'
    description: "\nEndpoints for managing storage"
